### ISSUE TITLE
Ростелеком

### ISSUE THREAD

**Issue by ring-rong** [12345qwert123456/Russian-block-bypass#1]
подойдут ли данные маршруты для роутеров ростелекома?

**Comment by 12345qwert123456** [comment]
Здравствуйте, под брендом "Ростелеком" выпускаются роутеры различных вендеров (Asus, D-link, TP-Link, ...) и настройка маршрутов зависит как от производителя так и от модели роутера.
Минимальные требования для роутера:
 - Поддержка VPN/Прокси
 - Возможность настройки маршрутов

Не знаю есть ли в других роутерах возможность загрузки маршрутов скриптом, но суть маршрутов в следующем
```
route ADD 74.119.0.0      MASK 255.255.0.0     0.0.0.0
          Подсеть         Маска подсети (/16)  Адрес шлюза VPN/Прокси
```
На большинстве роутеров есть возможность настроить это вручную.

---
Если напишите модель роутера попробую помочь

**Comment by ring-rong** [comment]
ага понял, спасибо за инфу, в моем случае это роутер от iskartel rt-gm-3

**Comment by 12345qwert123456** [comment]
Самого роутера у меня нет, так что могу судить только по информации из интернета.
Посмотрите на форуме [4pda.to](https://4pda.to/forum/index.php?showtopic=1033597&st=1220#entry121405226) есть настройка WireGuard на нём.
И маршруты, вроде как, можно настроить как через веб-интерфейс так и через консоль с Entware.

---
Если получится можете написать инструкцию по настройке роутеров `iskartel rt-gm-3` в **Pull request**, добавлю в репозиторий, может другим пригодится.

**Comment by ring-rong** [comment]
У меня тут немного поменялись обстоятельства, так что с ростелековским роутером я ковыряться не буду, но возможно поковыряюсь с tp-link, а вообще я немного не понимаю стоит ли эта игра свеч что именно делают данные маршруты, что они дают? Просто не совсем разбираюсь в теме и даже после прочтения описания не понимаю, то есть если мой айпишник банят сами openai, то помогут ли они (маршруты) мне зайти на сайт? Или они нужны только на тот случай если бы роскомнадзор банил openai?

**Comment by 12345qwert123456** [comment]
Помогут в обоих случаях.
Вообще наиболее эффективным решением является проксирование определенных доменных имен (например, instagram.com) с помощью клиента по типу Nekobox.
И тогда не нужно будет заботиться о том какой ip у веб-ресурса.
Данный список нужен для тех у кого роутер не поддерживает установку кастомных программ, либо нет железа для поднятия шлюза с прокси.
